### ISSUE TITLE
Fourth file is not available for download

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [t-systems-on-site-services-gmbh/german-wikipedia-text-corpus#1]
Hi!

from the four downloadable files named on this site, only three have a link. The fourth "wiki-all-shuf.tgz" is not downloadable and therefore, the archive can't be extracted.

Thanks for looking into this issue!

**Comment by PhilipMay** [comment]
The 4th is the result of the "concatenation" of the 3 parts.

See [Unpack](https://github.com/t-systems-on-site-services-gmbh/german-wikipedia-text-corpus#unpack)

PS: If this solves your issue - please close this.

PPS: If you are looking for a german text corpus you also might want to have a look here: https://german-nlp-group.github.io/projects/gc4-corpus.html

Thanks
Philip

**Comment by GitHubGeniusOverlord** [comment]
Thank You @PhilipMay
